version: '3'
services:
  utakata_golang_devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    image: utakata_golang_devcontainer_image
    container_name: utakata_golang_devcontainer_container
    volumes:
      - ../workspace:/workspace
    working_dir: /workspace
    command: /bin/sh
    tty: true
    stdin_open: true